apiVersion: apps/v1
kind: Deployment
metadata:
  name: apibackend
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: registry-journal
      containers:
        - name: apibackend
          image: apibackend
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: apibackend-env-secrets
