apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
        - name: appserver
          image: app-container
          ports:
            - containerPort: 8001
            - containerPort: 8002
