apiVersion: v1
kind: Service
metadata:
  name: appserver
spec:
  selector:
    app: appserver
  ports:
    - name: api
      port: 8001
      targetPort: 8001
    - name: frontend
      port: 8002
      targetPort: 8002
