---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: newsletters-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: newsletters.poudels.com
      http:
        paths:
          - path: /
            backend:
              serviceName: prod-envoy-proxy
              servicePort: 8000
