---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: alpine-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.alpinereader.com
    - http:
        paths:
          - path: /
            backend:
              serviceName: alpine-envoyproxy
              servicePort: 8000
