apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: alpine-
bases:
  - ../kube/apiserver
  - ../kube/emailprocessor
  - ../kube/envoy/
  - ../kube/rabbitmq
  - ../kube/staticserver/
  - ../kube/mailgun/
  - app/frontend/
resources:
  - pvc.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy/envoy.yaml
secretGenerator:
  - name: apiserver-env-secrets
    envs:
      - secrets/apiserver.env
  - name: emailprocessor-env-secrets
    envs:
      - secrets/emailprocessor.env
  - name: frontend-builder-env-secrets
    envs:
      - secrets/frontend.env
  - name: mailgun-env-secrets
    envs:
      - secrets/mailgun.env
  - name: rabbitmq-env-secrets
    envs:
      - secrets/rabbitmq.env
generatorOptions:
  labels:
    resource: alpine-config
images:
  - name: envoyproxy
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: rabbitmq
    newName: rabbitmq
    newTag: 3.8.9-management-alpine
  - name: apiserver
    newName: registry.digitalocean.com/journal/alpine/backend/apiserver
    newTag: ${COMMIT_HASH}
  - name: emailprocessor
    newName: registry.digitalocean.com/journal/alpine/backend/emailprocessor
    newTag: ${COMMIT_HASH}
  - name: frontend
    newName: registry.digitalocean.com/journal/alpine/frontend
    newTag: ${COMMIT_HASH}
  - name: staticserver
    newName: registry.digitalocean.com/journal/alpine/staticserver
    newTag: ${COMMIT_HASH}
  - name: mailgunserver
    newName: registry.digitalocean.com/journal/alpine/mailgunserver
    newTag: ${COMMIT_HASH}
