apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: alpine-
bases:
  - ../kube/apibackend
  - ../kube/envoy/
  - ../kube/staticserver/
  - ../kube/mailgun/
  - app/frontend/
resources:
  - pvc.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy/envoy.yaml
secretGenerator:
  - name: apibackend-env-secrets
    envs:
      - secrets/apibackend.env
  - name: frontend-builder-env-secrets
    envs:
      - secrets/frontend.env
  - name: mailgun-env-secrets
    envs:
      - secrets/mailgun.env
generatorOptions:
  labels:
    app: ${APP}
images:
  - name: envoyproxy
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: apibackend
    newName: registry.digitalocean.com/journal/alpine/apibackend
    newTag: ${COMMIT_HASH}
  - name: frontend
    newName: registry.digitalocean.com/journal/alpine/frontend
    newTag: ${COMMIT_HASH}
  - name: staticserver
    newName: registry.digitalocean.com/journal/alpine/staticserver
    newTag: ${COMMIT_HASH}
  - name: mailgunserver
    newName: registry.digitalocean.com/journal/alpine/mailgunserver
    newTag: ${COMMIT_HASH}
