apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
bases:
  - ../kube/apibackend
  - ../kube/envoy/
  - ../kube/staticserver/
  - app/frontend/
resources:
  - pvc.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy/envoy.yaml
secretGenerator:
  - name: apibackend-env-secrets
    envs:
      - secrets/apibackend.env
  - name: mysql-env-secrets
    envs:
      - secrets/mysql.env
  - name: frontend-builder-env-secrets
    envs:
      - secrets/frontend.env
generatorOptions:
  labels:
    app: ${APP}
images:
  - name: envoyproxy
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: mysql
    newName: mysql
    newTag: "8.0"
  - name: apibackend
    newName: registry.digitalocean.com/journal/newsletter/apibackend
    newTag: ${COMMIT_HASH}
  - name: frontend
    newName: registry.digitalocean.com/journal/newsletter/frontend
    newTag: ${COMMIT_HASH}
  - name: staticserver
    newName: registry.digitalocean.com/journal/newsletter/staticserver
    newTag: ${COMMIT_HASH}
