apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
# namespace: newsletters
bases:
  - ../kube/apibackend
  - ../kube/envoy/
  - ../kube/staticserver/
  - app/frontend/
resources:
  - pvc.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy/envoy.yaml
secretGenerator:
  - name: apibackend-env-secrets
    envs:
      - secrets/apibackend.env
  - name: mysql-env-secrets
    envs:
      - secrets/mysql.env
  - name: frontend-builder-env-secrets
    envs:
      - secrets/frontend.env
images:
  - name: envoy-container
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: mysql-container
    newName: mysql
    newTag: "8.0"
  - name: apibackend-container
    newName: registry.digitalocean.com/journal/apiserver
    newTag: v0.1.1
  - name: frontend-container
    newName: registry.digitalocean.com/journal/frontend-builder
    newTag: v0.1.1
  - name: staticserver-container
    newName: registry.digitalocean.com/journal/staticserver
    newTag: v0.1.1
