apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: registry-journal
      containers:
        - name: apiserver
          image: apiserver
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: apiserver-env-secrets
