apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tilt-
bases:
  - ../kube/apibackend
  - app/frontend
  - ../kube/envoy/
  - ../kube/mailgun/
  - ../kube/mysql
resources:
  - pvc.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy/envoy.yaml
secretGenerator:
  - name: apibackend-env-secrets
    envs:
      - secrets/apibackend.env
  - name: frontend-env-secrets
    envs:
      - secrets/frontend.env
  - name: mysql-env-secrets
    envs:
      - secrets/mysql.env
  - name: mailgun-env-secrets
    envs:
      - secrets/mailgun.env
images:
  - name: envoyproxy
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: mysql
    newName: mysql
    newTag: "8.0"
  - name: apibackend
    newName: tilt-apibackend
  - name: frontend
    newName: tilt-frontend
  - name: mailgunserver
    newName: tilt-mailgunserver
