namePrefix: tilt-
bases:
  - ../kube/app
  - ../kube/envoy/
  - ../kube/mysql
  - ../kube/staticserver/
resources:
  - pvc.yaml
secretGenerator:
  - name: appserver-env-secrets
    files:
      - secrets/MYSQL_HOST
      - secrets/MYSQL_USER
      - secrets/MYSQL_PASSWORD

      - secrets/GMAIL_CLIENT_ID
      - secrets/GMAIL_CLIENT_SECRET
      - secrets/GMAIL_API_KEY
      - secrets/GMAIL_REDIRECT_URL

      - secrets/LOGIN_COOKIE_SIGNING_KEY
      - secrets/NEWSLETTERS_STATIC_SERVER
  - name: mysql-env-secrets
    files:
      - secrets/MYSQL_ROOT_PASSWORD
      - secrets/MYSQL_DATABASE
      - secrets/MYSQL_USER
      - secrets/MYSQL_PASSWORD
images:
  - name: envoy-container
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: mysql-container
    newName: mysql
    newTag: "8.0"
  - name: app-container
    newName: tilt-app-container
  - name: staticserver-container
    newName: tilt-staticserver-container
