apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tilt-
bases:
  - ../kube/apibackend
  - ../kube/frontend
  - ../kube/envoy/
  - ../kube/mysql
  - ../kube/staticserver/
resources:
  - pvc.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy/envoy.yaml
secretGenerator:
  - name: apibackend-env-secrets
    envs:
      - secrets/apibackend.env
  - name: frontend-env-secrets
    envs:
      - secrets/frontend.env
  - name: mysql-env-secrets
    envs:
      - secrets/mysql.env
images:
  - name: envoy-container
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: mysql-container
    newName: mysql
    newTag: "8.0"
  - name: apibackend-container
    newName: tilt-apibackend-container
  - name: frontend-container
    newName: tilt-frontend-container
  - name: staticserver-container
    newName: tilt-staticserver-container
