apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tilt-
bases:
  - ../kube/apiserver
  - ../kube/emailprocessor
  - app/frontend
  - ../kube/envoy
  - ../kube/mailgun
  - ../kube/mysql
  - ../kube/rabbitmq
resources:
  - pvc.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy/envoy.yaml
secretGenerator:
  - name: apiserver-env-secrets
    envs:
      - secrets/apiserver.env
  - name: emailprocessor-env-secrets
    envs:
      - secrets/emailprocessor.env
  - name: frontend-env-secrets
    envs:
      - secrets/frontend.env
  - name: mysql-env-secrets
    envs:
      - secrets/mysql.env
  - name: mailgun-env-secrets
    envs:
      - secrets/mailgun.env
  - name: rabbitmq-env-secrets
    envs:
      - secrets/rabbitmq.env
images:
  - name: envoyproxy
    newName: envoyproxy/envoy
    newTag: v1.14.2
  - name: mysql
    newName: mysql
    newTag: "8.0"
  - name: rabbitmq
    newName: rabbitmq
    newTag: 3.8.9-management-alpine
  - name: apiserver
    newName: tilt-apiserver
  - name: emailprocessor
    newName: tilt-emailprocessor
  - name: frontend
    newName: tilt-frontend
  - name: mailgunserver
    newName: tilt-mailgunserver
