apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
