apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailgunserver
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mailgunserver
          image: mailgunserver
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: mailgun-env-secrets
