apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgress-volume
          persistentVolumeClaim:
            claimName: postgress-pvc
      containers:
        - name: postgres
          image: postgres-container
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/data/db"
              name: postgress-volume
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-env-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-env-secrets
                  key: POSTGRES_PASSWORD
