apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailprocessor
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: emailprocessor
          image: emailprocessor
          envFrom:
            - secretRef:
                name: emailprocessor-env-secrets
