apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoyproxy
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: envoy-config
      containers:
        - name: envoyproxy
          image: envoyproxy
          ports:
            - containerPort: 8000
            - containerPort: 5000
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/envoy
