apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: appserver
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: appserver-env-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appserver-env-secrets
                  key: POSTGRES_PASSWORD
